In [4]:
# Create a 3x3 array with random integers between 0 and 10
import numpy as np
arr = np.random.randint(0, 11, (3, 3))
print("Array:\n", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Std Dev:", np.std(arr))

Array:
 [[6 4 7]
 [9 3 5]
 [0 6 1]]
Sum: 41
Mean: 4.555555555555555
Std Dev: 2.7125679146074897


In [5]:
# 2. 1D array of 10 elements and cumulative sum
arr1d = np.arange(1, 11)
print("Cumulative sum:", np.cumsum(arr1d))

Cumulative sum: [ 1  3  6 10 15 21 28 36 45 55]


In [6]:
# 3. Two 2x3 arrays - element-wise operations
a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(1, 10, (2, 3))
print("Add:\n", a + b)
print("Subtract:\n", a - b)
print("Multiply:\n", a * b)
print("Divide:\n", a / b)

Add:
 [[ 4  3 15]
 [ 6  6 10]]
Subtract:
 [[ 0  1 -3]
 [ 2 -4  6]]
Multiply:
 [[ 4  2 54]
 [ 8  5 16]]
Divide:
 [[1.         2.         0.66666667]
 [2.         0.2        4.        ]]


In [7]:
# 4. 4x4 identity matrix
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# 5. Broadcasting
arr = np.array([5, 10, 15, 20, 25])
print("Divided by 5:", arr / 5)

Divided by 5: [1. 2. 3. 4. 5.]


In [9]:
# 6. Reshape 12 elements into 3x4 matrix
a = np.arange(12)
print(a.reshape(3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
# 7. Flatten 3x3 matrix
b = np.arange(9).reshape(3, 3)
print(b.flatten())

[0 1 2 3 4 5 6 7 8]


In [11]:
# 8. Stack 2 matrices
m1 = np.arange(9).reshape(3, 3)
m2 = np.ones((3, 3))
print("Horizontal:\n", np.hstack((m1, m2)))
print("Vertical:\n", np.vstack((m1, m2)))



Horizontal:
 [[0. 1. 2. 1. 1. 1.]
 [3. 4. 5. 1. 1. 1.]
 [6. 7. 8. 1. 1. 1.]]
Vertical:
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# 9. Concatenate along new axis
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.stack((a, b), axis=1))  # shape will be (3, 2)

[[1 4]
 [2 5]
 [3 6]]


In [13]:
# 10. Transpose and reshape
x = np.arange(6).reshape(2, 3)
print(x.T.reshape(3, 2))

[[0 3]
 [1 4]
 [2 5]]


In [14]:
# 11. 1D array extract from pos 2 to 10 with step 2
arr = np.arange(15)
print(arr[2:11:2])


[ 2  4  6  8 10]


In [15]:
# 12. Sub-matrix from 5x5
mat = np.arange(25).reshape(5, 5)
print(mat[1:4, 1:3])  # Rows 1 to 3, cols 1 to 2

[[ 6  7]
 [11 12]
 [16 17]]


In [16]:
# 13. Replace values >10 with 10
arr = np.arange(20)
arr[arr > 10] = 10
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 10 10 10 10 10 10 10 10 10]


In [17]:
# 14. Fancy indexing
arr = np.arange(10)
print(arr[[0, 2, 4, 6]])


[0 2 4 6]


In [18]:
# 15. Reverse using slicing
arr = np.arange(10)
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [19]:
# 16. Add 1x3 to 3x3
a = np.ones((3, 3))
b = np.array([1, 2, 3])
print(a + b)


[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [20]:
# 17. Multiply 1D array by scalar
arr = np.array([1, 2, 3, 4, 5])
print(arr * 3)



[ 3  6  9 12 15]


In [21]:
# 18. Subtract column vector from 3x3 matrix
matrix = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13]])
col = np.array([[1], [2], [3]])
print(matrix - col)

[[ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


In [27]:
#19.Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions.
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],
                     
                     [[7, 8, 9],
                      [10, 11, 12]]])

scalar = 5

result = array_3d + scalar

print("Original array:\n", array_3d)
print("\nAfter adding scalar:\n", result)

Original array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

After adding scalar:
 [[[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [31]:
#20. Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting.
A = np.array([[1],
              [2],
              [3],
              [4]])

B = np.array([[10, 20, 30, 40, 50]])

result = A + B

print("Array A (4,1):\n", A)
print("\nArray B (1,5):\n", B)
print("\nResult of A + B:\n", result)


Array A (4,1):
 [[1]
 [2]
 [3]
 [4]]

Array B (1,5):
 [[10 20 30 40 50]]

Result of A + B:
 [[11 21 31 41 51]
 [12 22 32 42 52]
 [13 23 33 43 53]
 [14 24 34 44 54]]


In [33]:
#21. Compute the square root of each element in a 2D array using vectorized operations.

array_2d = np.array([[1, 4, 9],
                     [16, 25, 36]])

sqrt_array = np.sqrt(array_2d)

print("Original array:\n", array_2d)
print("\nSquare root array:\n", sqrt_array)

Original array:
 [[ 1  4  9]
 [16 25 36]]

Square root array:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [34]:
#22.Calculate the dot product of two 1D arrays of size 5
# Two 1D arrays of size 5
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Calculate dot product
dot_product = np.dot(a, b)

print("Dot product:", dot_product)

Dot product: 550


In [35]:
#23. Perform element-wise comparison of two 1D arrays and return an array of boolean values indicating where the first array has larger elements

a = np.array([5, 10, 15, 20])
b = np.array([3, 12, 15, 18])

comparison = a > b

print("Array a:", a)
print("Array b:", b)
print("a > b:", comparison)


Array a: [ 5 10 15 20]
Array b: [ 3 12 15 18]
a > b: [ True False False  True]


In [36]:
#24.Create a 2D array and apply a vectorized operation to double the value of each element.

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Double each element using vectorized operation
doubled_array = array_2d * 2

print("Original array:\n", array_2d)
print("\nDoubled array:\n", doubled_array)

Original array:
 [[1 2 3]
 [4 5 6]]

Doubled array:
 [[ 2  4  6]
 [ 8 10 12]]


In [37]:
#25. Create a 1D array of 100 random integers and compute the sum of all even numbers using vectorized operations
# Create a 1D array of 100 random integers between 1 and 100
random_array = np.random.randint(1, 101, size=100)

even_numbers = random_array[random_array % 2 == 0]

sum_even = np.sum(even_numbers)

print("Random array:\n", random_array)
print("\nEven numbers:\n", even_numbers)
print("\nSum of even numbers:", sum_even)

Random array:
 [82 56 71 65 56  9 58 98 79 63  2 81 77 83 42 13 88 66 67 53 72 85 96 10
 12 31 43 46  4 76 56 70 22 76 24 94 36 89 21 41 66  3 94 56 60 25 54 55
 97  7 51 94 87  1 42 88 99 22  1 14 26 45 94 34 29 57 18 54  9 11 46  8
 66 97 92 57 33 55 35 89 29 35 39 23 15 48 84 51 96 51 72 60 58 93 75 78
 42 53 23 61]

Even numbers:
 [82 56 56 58 98  2 42 88 66 72 96 10 12 46  4 76 56 70 22 76 24 94 36 66
 94 56 60 54 94 42 88 22 14 26 94 34 18 54 46  8 66 92 48 84 96 72 60 58
 78 42]

Sum of even numbers: 2808


In [38]:
#26. Create a 3x3 matrix and find its determinant.

matrix = np.array([[1, 2, 3],
                   [0, 1, 4],
                   [5, 6, 0]])

determinant = np.linalg.det(matrix)

print("Matrix:\n", matrix)
print("\nDeterminant:", determinant)

Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]

Determinant: 0.9999999999999987


In [39]:
#27. Given a 2x2 matrix, compute its inverse and verify by multiplying with the original matrix to obtain the identity matrix.

matrix = np.array([[4, 7],
                   [2, 6]])

inverse_matrix = np.linalg.inv(matrix)

identity_matrix = np.dot(matrix, inverse_matrix)

print("Original matrix:\n", matrix)
print("\nInverse matrix:\n", inverse_matrix)
print("\nProduct (should be identity):\n", identity_matrix)

Original matrix:
 [[4 7]
 [2 6]]

Inverse matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Product (should be identity):
 [[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]


In [40]:
#28. Calculate the eigenvalues and eigenvectors of a 2x2 matrix
matrix = np.array([[4, 2],
                   [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Matrix:\n", matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Matrix:
 [[4 2]
 [1 3]]

Eigenvalues:
 [5. 2.]

Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [41]:
#29.Calculate the eigenvalues and eigenvectors of a 2x2 matrix

A = np.array([[2, 3],
              [4, 6]])

b = np.array([5, 10])

try:
    solution = np.linalg.solve(A, b)
    print("Solution:", solution)
except np.linalg.LinAlgError:
    print("System has no unique solution (singular matrix).")

System has no unique solution (singular matrix).


In [42]:
#30.Perform Singular Value Decomposition (SVD) on a 3x3 matrix and reconstruct the original matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

U, S, VT = np.linalg.svd(matrix)

S_matrix = np.zeros_like(matrix, dtype=float)
np.fill_diagonal(S_matrix, S)

reconstructed = U @ S_matrix @ VT

print("Original matrix:\n", matrix)
print("\nReconstructed matrix:\n", reconstructed)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
