In [27]:
# *11. Data Reshaping and Analysis

#1. *Use NumPy's reshape to change the shape of an array extracted from a DataFrame and analyze the reshaped data.

   
import numpy as np
import pandas as pd

df = pd.DataFrame({'A': range(1, 13)})
array = df['A'].values.reshape(3, 4)
print("Reshaped Array:\n", array)
print("Mean of each row:", np.mean(array, axis=1))


Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mean of each row: [ 2.5  6.5 10.5]


In [29]:
#2. *Stack two DataFrames vertically and use NumPy to analyze.*


df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
combined_df = pd.concat([df1, df2], axis=0)
print("Combined DF:\n", combined_df)

array = combined_df.values
print("Sum of all elements:", np.sum(array))

Combined DF:
    A  B
0  1  3
1  2  4
0  5  7
1  6  8
Sum of all elements: 36


In [30]:
#3. *Create a 3D array using NumPy and convert it into a MultiIndex DataFrame, then perform a group operation.*

data = np.random.randint(1, 10, size=(2, 3, 4))
df = pd.DataFrame(data.reshape(-1, 4),
                 index=pd.MultiIndex.from_product([[0, 1], [0, 1, 2]], names=['Block', 'Row']),
                 columns=['Col1', 'Col2', 'Col3', 'Col4'])
print(df.groupby(level='Block').sum())


       Col1  Col2  Col3  Col4
Block                        
0        18    16    13    12
1        18    14     6    17


In [31]:
# *12. Time Series Analysis*

#1. *Convert a column in a DataFrame to a time series and perform an operation.*


df = pd.DataFrame({'date': pd.date_range('2023-01-01', periods=5),
                  'value': [10, 20, 15, 25, 30]})
df.set_index('date', inplace=True)
print("Cumulative Sum:\n", df['value'].cumsum())


Cumulative Sum:
 date
2023-01-01     10
2023-01-02     30
2023-01-03     45
2023-01-04     70
2023-01-05    100
Name: value, dtype: int64


In [33]:
#2. *Calculate the moving average.*


df['moving_avg'] = df['value'].rolling(window=3).mean()
print(df)


            value  moving_avg
date                         
2023-01-01     10         NaN
2023-01-02     20         NaN
2023-01-03     15   15.000000
2023-01-04     25   20.000000
2023-01-05     30   23.333333


In [34]:
#3. *Use pd.to_datetime() and calculate time difference.*


df = pd.DataFrame({'timestamp': ['2024-01-01 10:00', '2024-01-01 12:30']})
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['time_diff'] = df['timestamp'].diff()
print(df)
   

            timestamp       time_diff
0 2024-01-01 10:00:00             NaT
1 2024-01-01 12:30:00 0 days 02:30:00


In [36]:
# *NumPy Questions*

#1. *Create a NumPy array of random numbers and normalize using min-max scaling.*

data = np.random.randint(1, 100, 10)
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized Data:", normalized)


Normalized Data: [0.26086957 0.95652174 0.30434783 1.         0.56521739 0.15217391
 0.60869565 0.         0.         0.        ]


In [37]:
#2. *Generate a 5x5 matrix and replace all occurrences of a value.*

 
matrix = np.random.randint(1, 5, size=(5, 5))
matrix[matrix == 3] = 0
print("Modified Matrix:\n", matrix)


Modified Matrix:
 [[1 0 1 2 4]
 [0 2 0 1 2]
 [1 4 1 1 1]
 [1 4 4 1 2]
 [4 4 0 4 0]]


In [38]:
#3. *Element-wise operations on two arrays.*


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [41]:
#4. *Solve a system of equations using NumPy.*

#   $$
 #  3x + 4y = 7\\
  # 5x + 2y = 8
   #$$


A = np.array([[3, 4], [5, 2]])
b = np.array([7, 8])
solution = np.linalg.solve(A, b)
print("x and y values:", solution)

x and y values: [1.28571429 0.78571429]


In [42]:
#5. *Broadcasting with 3x3 matrix and 1D array.*

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
array = np.array([1, 0, -1])
result = matrix + array
print(result)

[[2 2 2]
 [5 5 5]
 [8 8 8]]


In [43]:
#6. *Create a 3x3 identity matrix.*

  
identity = np.eye(3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
